# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [];



  services.xserver.videoDrivers = ["modesetting"];
  boot.initrd.availableKernelModules = [ "vfio-pci" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" "vfio" "vfio_iommu_type1" "vfio_pci" "vfio_virqfd" "wl"];
  boot.extraModulePackages = [  ];



  # boot.initrd.luks.devices = [
  #   {
  #     name = "LUKS-BIRDPERSON-ROOT";
  #     device = "/dev/disk/by-partlabel/BIRDPERSON-ROOT";
  #     allowDiscards = true;
  #   }

  #   {
  #     name = "LUKS-BIRDPERSON-ARCHIVES";
  #     device = "/dev/disk/by-partlabel/BIRDPERSON-ARCHIVES";
  #     allowDiscards = true;
  #   }

  # ];



  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };



  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-partlabel/EFI-BIRDPERSON";
  #     fsType = "vfat";
  #   };

  # swapDevices =
  #   [ { device = "/dev/disk/by-label/swap"; }
  #   ];

  # nix.maxJobs = lib.mkDefault 8;
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
