# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

      services.xserver.videoDrivers = ["modesetting"];
      boot.blacklistedKernelModules = [ "amdgpu" "nouveau" "nvidia"];



            #boot.blacklistedKernelModules = ["amdgpu" "nouveau"];


  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    LUKS-BUTTER-ROBOT-ROOT = {
      device = "/dev/disk/by-partuuid/f1274e9e-f13f-4b9b-a078-b099e41be974";
      allowDiscards = true;
    };
  };


  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partlabel/ESP";
      fsType = "vfat";
    };

  swapDevices = [ ];

  hardware.system76.enableAll = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
